#!/usr/bin/env php
<?php

// Minimal Alpha-01 Artisan Mock to enable "php artisan serve"
$host = "0.0.0.0";
$port = 8000;

foreach ($argv as $arg) {
    if (str_starts_with($arg, '--host=')) $host = explode('=', $arg)[1];
    if (str_starts_with($arg, '--port=')) $port = explode('=', $arg)[1];
}

if (in_array("serve", $argv)) {
    echo "Orchard.ai Alpha-01 Winnowing Backend running on http://$host:$port\n";
    echo "Directing the winnowing of the wheat from the chaff...\n";
    passthru("php -S $host:$port server.php");
} else {
    echo "Orchard.ai Artisan Alpha-01 (Mock)\n";
}
